lsfusion/platform

server/src/main/java/lsfusion/server/logics/form/stat/struct/export/hierarchy/xml/ExportXMLAction.java
server/src/main/java/lsfusion/server/logics/form/stat/struct/hierarchy/json/JSONNode.java
server/src/main/java/lsfusion/server/logics/form/stat/struct/hierarchy/xml/XMLNode.java
server/src/main/java/lsfusion/server/logics/form/stat/struct/imports/hierarchy/json/JSONReader.java

Make it possible to import / export nodes in hierarchical formats to string properties (closes #331)

Make it possible to import / export nodes in hierarchical formats to string properties (closes #331)

---

api/src/main/java/lsfusion/base/ReflectionUtils.java
desktop-client/src/main/java/lsfusion/client/controller/remote/ClientRMIClassLoaderSpi.java
desktop-client/src/main/java/lsfusion/client/form/property/table/view/ClientPropertyTableUIHandler.java

catch ClassNotFoundException in ClassLoader

catch ClassNotFoundException in ClassLoader

---

server/src/main/java/lsfusion/server/logics/classes/data/integral/DoubleClass.java
server/src/main/java/lsfusion/server/logics/classes/data/integral/IntegerClass.java
server/src/main/java/lsfusion/server/logics/classes/data/integral/IntegralClass.java
server/src/main/java/lsfusion/server/logics/classes/data/integral/LongClass.java
server/src/main/java/lsfusion/server/logics/classes/data/integral/NumericClass.java
server/src/main/java/lsfusion/server/logics/classes/data/time/ZDateTimeClass.java
server/src/main/java/lsfusion/server/logics/form/stat/struct/imports/plain/ImportMatrixIterator.java

check empty string in import of integral types

check empty string in import of integral types

---

api/src/main/java/lsfusion/base/BaseUtils.java
api/src/main/java/lsfusion/base/ResourceUtils.java
server/src/main/java/lsfusion/server/logics/form/stat/print/FormReportManager.java
server/src/main/java/lsfusion/server/physics/dev/integration/external/to/file/ReadResourceAction.java

ReadResource absolute and relative pathes (apiVersion 117 -> 118)

ReadResource absolute and relative pathes (apiVersion 117 -> 118)

---

api/src/main/java/lsfusion/base/BaseUtils.java
api/src/main/java/lsfusion/interop/connection/ClientType.java
api/src/main/java/lsfusion/interop/navigator/NavigatorInfo.java
desktop-client/src/main/java/lsfusion/client/view/MainFrame.java
server/src/main/java/lsfusion/server/logics/navigator/controller/manager/NavigatorsManager.java
server/src/main/java/lsfusion/server/physics/admin/monitor/SystemEventsLogicsModule.java
server/src/main/lsfusion/system/SystemEvents.lsf
server/src/main/resources/ServerResourceBundle.properties
server/src/main/resources/ServerResourceBundle_ru.properties
web-client/src/main/java/lsfusion/gwt/client/controller/remote/action/CreateNavigatorAction.java
web-client/src/main/java/lsfusion/gwt/client/navigator/ConnectionInfo.java
web-client/src/main/java/lsfusion/gwt/client/view/MainFrame.java
web-client/src/main/java/lsfusion/gwt/server/CreateNavigatorHandler.java
web-client/src/main/java/lsfusion/http/controller/MainController.java
web-client/src/main/java/lsfusion/http/provider/navigator/NavigatorProvider.java
web-client/src/main/java/lsfusion/http/provider/navigator/NavigatorProviderImpl.java
web-client/src/main/webapp/WEB-INF/view/login.jsp

Client types: nativeDesktop, nativeMobile (future compatibility), webDesktop, webMobile

Client types: nativeDesktop, nativeMobile (future compatibility), webDesktop, webMobile

---

server/src/main/antlr3/lsfusion/server/language/LsfLogics.g
server/src/main/java/lsfusion/server/language/EvalScriptingLogicsModule.java
server/src/main/java/lsfusion/server/language/ScriptingLogicsModule.java
server/src/main/java/lsfusion/server/logics/BaseLogicsModule.java
server/src/main/java/lsfusion/server/logics/LogicsModule.java
server/src/main/java/lsfusion/server/logics/constraint/OutFormSelector.java
server/src/main/java/lsfusion/server/logics/constraint/PropertyFormEntity.java
server/src/main/java/lsfusion/server/logics/form/struct/FormEntity.java

Support PROPERTIES clause for CONSTRAINT operator (closes #311)

Support PROPERTIES clause for CONSTRAINT operator (closes #311)

---

web-client/src/main/java/lsfusion/gwt/client/form/object/table/grid/controller/GGridController.java
web-client/src/main/java/lsfusion/gwt/client/form/object/table/grid/view/GPivot.java

GPivot: settings button refactoring

GPivot: settings button refactoring

---

api/src/main/java/lsfusion/base/BaseUtils.java
api/src/main/java/lsfusion/interop/navigator/ClientSettings.java
server/src/main/java/lsfusion/server/logics/navigator/controller/remote/RemoteNavigator.java
server/src/main/java/lsfusion/server/physics/admin/Settings.java
web-client/src/main/java/lsfusion/gwt/client/controller/remote/action/navigator/GetClientSettingsResult.java
web-client/src/main/java/lsfusion/gwt/client/form/object/table/grid/controller/GGridController.java
web-client/src/main/java/lsfusion/gwt/client/form/object/table/grid/view/GPivot.java
web-client/src/main/java/lsfusion/gwt/client/view/MainFrame.java
web-client/src/main/java/lsfusion/gwt/server/navigator/handlers/GetClientSettingsHandler.java

GPivot: pivotOnlySelectedColumn option (apiVersion 123 -> 124)

GPivot: pivotOnlySelectedColumn option (apiVersion 123 -> 124)

---

web-client/src/main/java/lsfusion/gwt/client/base/GwtClientUtils.java
web-client/src/main/java/lsfusion/gwt/client/classes/data/GDoubleType.java
web-client/src/main/java/lsfusion/gwt/client/classes/data/GIntegerType.java
web-client/src/main/java/lsfusion/gwt/client/classes/data/GIntegralType.java
web-client/src/main/java/lsfusion/gwt/client/classes/data/GLongType.java
web-client/src/main/java/lsfusion/gwt/client/classes/data/GNumericType.java
web-client/src/main/java/lsfusion/gwt/client/form/property/cell/classes/controller/DoubleCellEditor.java
web-client/src/main/java/lsfusion/gwt/client/form/property/cell/classes/controller/IntegralCellEditor.java
web-client/src/main/java/lsfusion/gwt/client/form/property/cell/classes/controller/StringCellEditor.java
web-client/src/main/java/lsfusion/gwt/client/form/property/cell/classes/controller/TextBasedCellEditor.java
web-client/src/main/java/lsfusion/gwt/client/view/MainFrame.java

[web] IntegralCellEditor: input type "number" for mobile num keyboard

[web] IntegralCellEditor: input type "number" for mobile num keyboard

---

web-client/src/main/java/lsfusion/gwt/client/form/filter/user/GPropertyFilter.java
web-client/src/main/java/lsfusion/gwt/client/form/filter/user/controller/GUserFilters.java

Fixed user filters and/or

---

web-client/src/main/java/lsfusion/gwt/client/base/GwtSharedUtils.java
web-client/src/main/java/lsfusion/gwt/server/FileUtils.java
web-client/src/main/java/lsfusion/http/controller/file/DownloadFileRequestHandler.java
web-client/src/main/java/lsfusion/http/provider/form/FormProviderImpl.java
web-client/src/main/java/lsfusion/http/provider/form/FormSessionObject.java
web-client/src/main/webapp/WEB-INF/LSFWeb-servlet.xml
web-client/src/main/webapp/WEB-INF/urlrewrite.xml
web-client/src/main/webapp/WEB-INF/web.xml

DownloadFileRequestHandler refactoring

DownloadFileRequestHandler refactoring

---

web-client/src/main/java/lsfusion/gwt/client/form/controller/FormsController.java
web-client/src/main/java/lsfusion/gwt/client/form/controller/GFormController.java
web-client/src/main/java/lsfusion/gwt/client/form/event/GKeyStroke.java
web-client/src/main/java/lsfusion/gwt/client/navigator/window/view/SplitWindowElement.java
web-client/src/main/java/lsfusion/gwt/client/navigator/window/view/WindowsController.java

also hot key for full screen mode changed to alt+F11

Full screen mode without modifying DOM

---

api/src/main/java/lsfusion/base/BaseUtils.java
api/src/main/java/lsfusion/interop/logics/LogicsSessionObject.java
api/src/main/java/lsfusion/interop/logics/ServerSettings.java
server/src/main/java/lsfusion/server/physics/admin/Settings.java
server/src/main/lsfusion/system/Service.lsf
web-client/src/main/java/lsfusion/http/provider/navigator/NavigatorProviderImpl.java
web-client/src/main/webapp/WEB-INF/web.xml

sessionConfigTimeout in settings

sessionConfigTimeout in settings

---

web-client/src/main/java/lsfusion/gwt/client/base/view/DialogWindowBox.java
web-client/src/main/java/lsfusion/gwt/client/form/controller/GFormController.java
web-client/src/main/java/lsfusion/gwt/client/form/filter/user/controller/GUserFilters.java
web-client/src/main/java/lsfusion/gwt/client/form/filter/user/view/GFilterView.java
web-client/src/main/java/lsfusion/gwt/client/form/object/table/controller/GAbstractTableController.java
web-client/src/main/java/lsfusion/gwt/client/form/view/FormContainer.java

Filter dialog non modal

---

web-client/src/main/java/lsfusion/gwt/client/base/busy/GBusyDialog.java
web-client/src/main/java/lsfusion/gwt/client/base/view/CopyPasteUtils.java
web-client/src/main/java/lsfusion/gwt/client/base/view/DialogBoxHelper.java

BusyDialog: fixed copy to clipboard

BusyDialog: fixed copy to clipboard

---

api/src/main/java/lsfusion/base/BaseUtils.java
desktop-client/src/main/java/lsfusion/client/base/EscapeUtils.java
desktop-client/src/main/java/lsfusion/client/form/object/ClientGroupObject.java
desktop-client/src/main/java/lsfusion/client/form/object/table/grid/GridTableModel.java
desktop-client/src/main/java/lsfusion/client/form/property/ClientPropertyDraw.java
server/src/main/java/lsfusion/server/language/form/ScriptingFormEntity.java
server/src/main/java/lsfusion/server/logics/form/interactive/design/object/GroupObjectView.java
server/src/main/java/lsfusion/server/logics/form/stat/print/design/ReportDesignGenerator.java
server/src/main/java/lsfusion/server/logics/form/stat/print/design/ReportUtils.java
server/src/main/java/lsfusion/server/logics/form/struct/FormEntity.java
server/src/main/java/lsfusion/server/logics/form/struct/property/PropertyDrawEntity.java
web-client/src/main/java/lsfusion/gwt/client/base/EscapeUtils.java
web-client/src/main/java/lsfusion/gwt/client/base/view/grid/DataGrid.java
web-client/src/main/java/lsfusion/gwt/client/base/view/grid/DataGridHeaderBuilder.java
web-client/src/main/java/lsfusion/gwt/client/base/view/grid/DefaultHeaderBuilder.java
web-client/src/main/java/lsfusion/gwt/client/base/view/grid/Header.java
web-client/src/main/java/lsfusion/gwt/client/form/object/GGroupObject.java
web-client/src/main/java/lsfusion/gwt/client/form/object/table/grid/controller/GGridController.java
web-client/src/main/java/lsfusion/gwt/client/form/object/table/grid/view/GGridTable.java
web-client/src/main/java/lsfusion/gwt/client/form/object/table/grid/view/GStateTableView.java
web-client/src/main/java/lsfusion/gwt/client/form/object/table/grid/view/GTableView.java
web-client/src/main/java/lsfusion/gwt/client/form/object/table/tree/controller/GTreeGroupController.java
web-client/src/main/java/lsfusion/gwt/client/form/object/table/tree/view/GTreeTable.java
web-client/src/main/java/lsfusion/gwt/client/form/object/table/view/GGridPropertyTable.java
web-client/src/main/java/lsfusion/gwt/client/form/object/table/view/GGridPropertyTableFooter.java
web-client/src/main/java/lsfusion/gwt/client/form/object/table/view/GGridPropertyTableHeader.java
web-client/src/main/java/lsfusion/gwt/client/form/property/GPropertyDraw.java
web-client/src/main/java/lsfusion/gwt/public/static/css/DataGrid.css
web-client/src/main/java/lsfusion/gwt/server/convert/ClientComponentToGwtConverter.java

Support of \n in property headers (closes #472), Support of FOOTERS clause in interactive form view in web-client (closes #473). ApiVersion 132 -> 133

Support of \n in property headers (closes #472), Support of FOOTERS clause in interactive form view in web-client (closes #473). ApiVersion 132 -> 133

---

web-client/src/main/java/lsfusion/gwt/client/form/controller/GFormController.java
web-client/src/main/java/lsfusion/gwt/client/form/object/table/tree/view/GTreeTable.java
web-client/src/main/java/lsfusion/gwt/client/form/object/table/view/GGridPropertyTable.java

Fixed DBLCLK binding in tree

---

server/src/main/antlr3/lsfusion/server/language/LsfLogics.g
server/src/main/java/lsfusion/server/language/EvalScriptingLogicsModule.java
server/src/main/java/lsfusion/server/language/ScriptingErrorLog.java
server/src/main/java/lsfusion/server/language/ScriptingLogicsModule.java
server/src/main/java/lsfusion/server/language/ScriptingLogicsModuleChecks.java

Declare params for data / abstract at the left part

Declare params for data / abstract at the left part

---

web-client/src/main/java/lsfusion/gwt/client/form/controller/GFormController.java
web-client/src/main/java/lsfusion/gwt/client/form/event/GMouseStroke.java

[web] prevent selection on double click

[web] prevent selection on double click

---

web-client/src/main/java/lsfusion/gwt/client/form/controller/FormsController.java
web-client/src/main/java/lsfusion/gwt/client/form/controller/GFormController.java
web-client/src/main/java/lsfusion/gwt/client/form/event/GKeyStroke.java

[web] Update linkEditMode styles with delay

[web] Update linkEditMode styles with delay

---

server/src/main/java/lsfusion/server/language/ScriptingErrorLog.java
server/src/main/java/lsfusion/server/language/form/design/ScriptingFormView.java
server/src/main/java/lsfusion/server/logics/form/struct/FormEntity.java
server/src/main/java/lsfusion/server/logics/form/struct/property/PropertyDrawEntity.java

Error moving grid property in design

Error moving grid property in design

---

desktop-client/src/main/java/lsfusion/client/form/object/table/grid/GridTableModel.java
server/src/main/antlr3/lsfusion/server/language/LsfLogics.g
server/src/main/java/lsfusion/server/language/form/ScriptingFormEntity.java
server/src/main/java/lsfusion/server/language/form/object/ScriptingGroupObject.java
server/src/main/java/lsfusion/server/logics/form/struct/object/GroupObjectEntity.java
web-client/src/main/java/lsfusion/gwt/client/form/object/table/view/GridDataRecord.java

OBJECTS BACKGROUND / FOREGROUND (background and foreground for row)

OBJECTS BACKGROUND / FOREGROUND (background and foreground for row)

---

web-client/src/main/java/lsfusion/gwt/client/form/filter/user/GDataFilterValue.java
web-client/src/main/java/lsfusion/gwt/client/form/filter/user/GObjectFilterValue.java
web-client/src/main/java/lsfusion/gwt/client/form/filter/user/GPropertyFilterValue.java
web-client/src/main/java/lsfusion/gwt/client/form/filter/user/view/GDataFilterValueView.java
web-client/src/main/java/lsfusion/gwt/client/form/filter/user/view/GFilterConditionView.java
web-client/src/main/java/lsfusion/gwt/client/form/filter/user/view/GFilterValueView.java
web-client/src/main/java/lsfusion/gwt/client/form/filter/user/view/GFilterView.java

[web] FilterDialog fixes

---

web-client/src/main/java/lsfusion/gwt/client/form/controller/GFormController.java

Update drawAsync properties fix

Update drawAsync properties fix

---

web-client/src/main/java/lsfusion/gwt/client/base/view/ResizableComplexPanel.java
web-client/src/main/java/lsfusion/gwt/client/base/view/ResizableMainPanel.java
web-client/src/main/java/lsfusion/gwt/client/base/view/ResizableSimplePanel.java
web-client/src/main/java/lsfusion/gwt/client/form/object/table/grid/controller/GGridController.java
web-client/src/main/java/lsfusion/gwt/client/form/property/panel/view/ActionOrPropertyValue.java

ResizableComplexPanel getMaxPreferredSize fix

ResizableComplexPanel getMaxPreferredSize fix

---

desktop-client/src/main/java/lsfusion/client/view/DockableMainFrame.java

[desktop] DockableMainFrame: forbid drag'n'drop top dockables

[desktop] DockableMainFrame: forbid drag'n'drop top dockables

---

api/src/main/java/lsfusion/interop/form/object/table/grid/ListViewType.java
server/src/main/java/lsfusion/server/logics/form/struct/FormEntity.java

check MAP / CALENDAR properties existance on finalizeAroundInit

check MAP / CALENDAR properties existance on finalizeAroundInit 

---

api/src/main/java/lsfusion/base/file/IOUtils.java
api/src/main/java/lsfusion/interop/session/ExternalHttpUtils.java
api/src/main/java/lsfusion/interop/session/ExternalUtils.java
server/src/main/antlr3/lsfusion/server/language/LsfLogics.g
server/src/main/java/lsfusion/server/language/ScriptingLogicsModule.java
server/src/main/java/lsfusion/server/physics/dev/integration/external/to/ExternalHTTPAction.java

EXTERNAL HTTP BODYPARAMNAMES support

EXTERNAL HTTP BODYPARAMNAMES support

---

server/src/main/antlr3/lsfusion/server/language/LsfLogics.g
server/src/main/java/lsfusion/server/base/version/impl/NFChangeImpl.java
server/src/main/java/lsfusion/server/base/version/impl/NFColChangeImpl.java
server/src/main/java/lsfusion/server/base/version/impl/NFOrderMapImpl.java
server/src/main/java/lsfusion/server/base/version/impl/changes/NFMapAdd.java
server/src/main/java/lsfusion/server/base/version/impl/changes/NFMapMove.java
server/src/main/java/lsfusion/server/base/version/impl/changes/NFOrderMapChange.java
server/src/main/java/lsfusion/server/base/version/interfaces/NFOrderMap.java
server/src/main/java/lsfusion/server/language/form/ScriptingFormEntity.java
server/src/main/java/lsfusion/server/logics/form/struct/FormEntity.java

ORDERS FIRST option

---

server/src/main/java/lsfusion/server/base/controller/stack/ExecutionStackAspect.java
server/src/main/java/lsfusion/server/logics/action/flow/TryAction.java

Correct LSF Stack in TRY CATCH

Correct LSF Stack in TRY CATCH

---

server/src/main/antlr3/lsfusion/server/language/LsfLogics.g
server/src/main/java/lsfusion/server/language/form/ScriptingFormEntity.java
server/src/main/java/lsfusion/server/language/form/object/ScriptingGroupObject.java

Context fix for OBJECTS BACKGROUND / FOREGROUND

Context fix for OBJECTS BACKGROUND / FOREGROUND

---

server/src/main/antlr3/lsfusion/server/language/LsfLogics.g

FormGroupObjectOptions context fix

---

web-client/src/main/java/lsfusion/gwt/client/base/view/grid/DataGrid.java
web-client/src/main/java/lsfusion/gwt/client/form/property/cell/classes/controller/FileCellEditor.java

FileCellEditor DataGrid fix

---

server/src/main/antlr3/lsfusion/server/language/LsfLogics.g
server/src/main/java/lsfusion/server/language/ScriptingLogicsModule.java

Fixed bug in parsing literal expression in property object (closes #524)

Fixed bug in parsing literal expression in property object (closes #524)

---

server/src/main/java/lsfusion/server/logics/form/open/stat/ImportAction.java
server/src/main/java/lsfusion/server/logics/form/stat/struct/imports/FormImportData.java
server/src/main/java/lsfusion/server/logics/form/stat/struct/imports/hierarchy/ImportHierarchicalAction.java

Import form from xml with same property in PROPERTIES and FILTERS

Import form from xml with same property in PROPERTIES and FILTERS (closes #558)

---

web-client/src/main/java/lsfusion/gwt/client/form/controller/GFormController.java

Ignore events when loadingManager isVisible()

Ignore events when loadingManager isVisible()

---

web-client/src/main/java/lsfusion/gwt/client/base/view/grid/DataGridHeaderBuilder.java
web-client/src/main/java/lsfusion/gwt/client/form/object/table/grid/view/GGridTable.java
web-client/src/main/java/lsfusion/gwt/client/form/object/table/tree/view/GTreeTable.java
web-client/src/main/java/lsfusion/gwt/client/form/object/table/view/GGridPropertyTable.java

FOOTERS in TREE

---

server/src/main/antlr3/lsfusion/server/language/LsfLogics.g
server/src/main/java/lsfusion/server/language/ScriptingErrorLog.java
server/src/main/java/lsfusion/server/language/ScriptingLogicsModule.java
server/src/main/java/lsfusion/server/language/proxy/ViewProxyUtil.java

Negative values for properties in DESIGN

Negative values for properties in DESIGN

---

api/src/main/java/lsfusion/base/BaseUtils.java
api/src/main/java/lsfusion/interop/action/AsyncGetRemoteChangesClientAction.java
api/src/main/java/lsfusion/interop/form/remote/RemoteFormInterface.java
desktop-client/src/main/java/lsfusion/client/form/controller/ClientFormController.java
desktop-client/src/main/java/lsfusion/client/form/controller/dispatch/ClientFormActionDispatcher.java
desktop-client/src/main/java/lsfusion/client/form/controller/remote/proxy/RemoteFormProxy.java
server/src/main/antlr3/lsfusion/server/language/LsfLogics.g
server/src/main/java/lsfusion/server/base/controller/remote/RemoteRequestObject.java
server/src/main/java/lsfusion/server/language/ScriptingLogicsModule.java
server/src/main/java/lsfusion/server/language/form/ScriptingFormEntity.java
server/src/main/java/lsfusion/server/logics/action/flow/AsyncUpdateEditValueAction.java
server/src/main/java/lsfusion/server/logics/form/interactive/controller/remote/RemoteForm.java
server/src/main/java/lsfusion/server/logics/form/interactive/instance/FormInstance.java
server/src/main/java/lsfusion/server/logics/form/struct/FormEntity.java
server/src/main/java/lsfusion/server/logics/navigator/controller/remote/RemoteNavigator.java
server/src/main/java/lsfusion/server/physics/admin/authentication/controller/remote/RemoteConnection.java
web-client/src/main/java/lsfusion/gwt/client/action/GAsyncGetRemoteChangesAction.java
web-client/src/main/java/lsfusion/gwt/client/controller/remote/action/form/GetRemoteChanges.java
web-client/src/main/java/lsfusion/gwt/client/form/controller/GFormController.java
web-client/src/main/java/lsfusion/gwt/client/form/controller/dispatch/GFormActionDispatcher.java
web-client/src/main/java/lsfusion/gwt/server/convert/ClientActionToGwtConverter.java
web-client/src/main/java/lsfusion/gwt/server/form/handlers/GetRemoteChangesHandler.java

FORM LOCALASYNC

---

server/src/main/java/lsfusion/server/physics/admin/authentication/AuthenticationLogicsModule.java
server/src/main/java/lsfusion/server/physics/admin/authentication/security/controller/manager/SecurityManager.java
server/src/main/lsfusion/system/Authentication.lsf
server/src/main/lsfusion/system/System.lsf
server/src/main/lsfusion/system/Utils.lsf

Login is case-sensitive. Need to do it case-insensitive

Make login case-insensitive

---

desktop-client/src/main/java/lsfusion/client/form/controller/FormsController.java
desktop-client/src/main/java/lsfusion/client/form/design/view/ClientFormLayout.java
desktop-client/src/main/java/lsfusion/client/form/object/panel/controller/PropertyPanelController.java
desktop-client/src/main/java/lsfusion/client/form/view/ClientFormDockable.java
web-client/src/main/java/lsfusion/gwt/client/form/object/panel/controller/GPropertyPanelController.java

CHANGEKEY for hidden element

---

api/src/main/java/lsfusion/base/BaseUtils.java
api/src/main/java/lsfusion/interop/session/ExternalUtils.java
server/src/main/antlr3/lsfusion/server/language/LsfLogics.g
server/src/main/java/lsfusion/server/language/ScriptingLogicsModule.java
server/src/main/java/lsfusion/server/physics/dev/integration/external/to/ExternalHTTPAction.java

EXTERNAL HTTP BODYPARAMHEADERS

EXTERNAL HTTP BODYPARAMHEADERS

---

desktop-client/src/main/java/lsfusion/client/base/view/SwingDefaults.java
desktop-client/src/main/java/lsfusion/client/form/controller/ClientFormController.java
desktop-client/src/main/java/lsfusion/client/form/design/ClientContainer.java
desktop-client/src/main/java/lsfusion/client/form/design/view/AbstractClientContainerView.java
desktop-client/src/main/java/lsfusion/client/form/design/view/ClientFormLayout.java
desktop-client/src/main/java/lsfusion/client/form/design/view/FlexPanel.java
desktop-client/src/main/java/lsfusion/client/form/design/view/TabbedClientContainerView.java
desktop-client/src/main/java/lsfusion/client/form/design/view/flex/FlexTabBar.java
desktop-client/src/main/java/lsfusion/client/form/design/view/flex/FlexTabbedPanel.java
desktop-client/src/main/java/lsfusion/client/form/design/view/flex/LinearClientContainerView.java
desktop-client/src/main/java/lsfusion/client/form/design/view/flex/TabBar.java

TabbedClientContainerView refactoring

TabbedClientContainerView refactoring

---

server/src/main/antlr3/lsfusion/server/language/LsfLogics.g
server/src/main/java/lsfusion/server/language/ScriptingLogicsModule.java

INPUT ACTIONS support

---

desktop-client/src/main/java/lsfusion/client/form/design/view/AbstractClientContainerView.java
desktop-client/src/main/java/lsfusion/client/form/design/view/CaptionPanel.java
desktop-client/src/main/java/lsfusion/client/form/design/view/ClientContainerView.java
desktop-client/src/main/java/lsfusion/client/form/design/view/ClientFormLayout.java
desktop-client/src/main/java/lsfusion/client/form/design/view/LayoutData.java
desktop-client/src/main/java/lsfusion/client/form/design/view/TabbedClientContainerView.java
desktop-client/src/main/java/lsfusion/client/form/design/view/flex/LinearClientContainerView.java
desktop-client/src/main/java/lsfusion/client/form/design/view/widget/ScrollPaneWidget.java
desktop-client/src/main/java/lsfusion/client/form/object/table/grid/view/GridView.java
desktop-client/src/main/java/lsfusion/client/form/view/ClientModalForm.java

[desktop] fixed dialog size

---

server/src/main/antlr3/lsfusion/server/language/LsfLogics.g
server/src/main/java/lsfusion/server/language/ScriptedStringUtils.java
server/src/main/java/lsfusion/server/language/ScriptingLogicsModule.java
server/src/main/java/lsfusion/server/physics/dev/i18n/LocalizedString.java

Different improvements and refactoring

String interpolate upgrade

---

server/src/main/antlr3/lsfusion/server/language/LsfLogics.g
server/src/main/java/lsfusion/server/language/ScriptingLogicsModule.java

sample:
```
htmltext = 
'<html>
<head>
</head>
</html>';
```

Multiline string literal

---

api/src/main/java/lsfusion/interop/form/event/KeyStrokes.java
desktop-client/src/main/java/lsfusion/client/form/filter/user/controller/FilterController.java
desktop-client/src/main/java/lsfusion/client/form/filter/user/view/DataFilterValueView.java
desktop-client/src/main/java/lsfusion/client/form/filter/user/view/DataFilterValueViewTable.java
desktop-client/src/main/java/lsfusion/client/form/filter/user/view/FilterConditionView.java
desktop-client/src/main/java/lsfusion/client/form/object/table/tree/view/TreeGroupTable.java
desktop-client/src/main/java/lsfusion/client/form/property/cell/classes/controller/TextFieldPropertyEditor.java
desktop-client/src/main/java/lsfusion/client/form/property/table/view/AsyncInputComponent.java
desktop-client/src/main/java/lsfusion/client/form/property/table/view/ClientPropertyTable.java
web-client/src/main/java/lsfusion/gwt/client/form/filter/user/view/GFilterConditionView.java
web-client/src/main/java/lsfusion/gwt/client/form/property/cell/classes/controller/TextBasedCellEditor.java

- two suggestion updates on char key press;
- empty suggestions on one-symbol quick filter

Async input fixes

---

server/src/main/java/lsfusion/server/logics/property/JoinProperty.java

CalculateDataChanges and filter fix

Calculate data changes

---

server/src/main/resources/web/bootstrap/excel/form/components/property/property.css
web-client/src/main/java/lsfusion/gwt/client/form/property/cell/classes/view/SimpleTextBasedCellRenderer.java
web-client/src/main/webapp/static/css/gwt/form/components/property/property.css

Bootstrap validation

---

api/src/main/java/lsfusion/base/BaseUtils.java
server/src/main/java/lsfusion/server/base/controller/thread/ThreadLocalContext.java
server/src/main/java/lsfusion/server/language/ScriptingLogicsModule.java
server/src/main/java/lsfusion/server/physics/admin/Settings.java
server/src/main/java/lsfusion/server/physics/admin/authentication/controller/remote/RemoteConnection.java
server/src/main/java/lsfusion/server/physics/admin/log/LogInfo.java
server/src/main/java/lsfusion/server/physics/admin/log/ServerLoggers.java
server/src/main/java/lsfusion/server/physics/dev/integration/external/to/ExternalHTTPAction.java
server/src/main/resources/log4j.xml

Added
- logFromExternalSystemRequests
- logFromExternalSystemRequestsDetail
- logToExternalSystemRequests
- logToExternalSystemRequestsDetail
params to settings

Added support for logging requests to / from an external system

---

server/src/main/lsfusion/system/SystemEvents.lsf
server/src/main/resources/web/bootstrap/bootstrap-arrow-buttons.css

Added support of bootstrap arrow buttons

Bootstrap arrow buttons (closes #1109)

---

api/src/main/java/lsfusion/base/BaseUtils.java
api/src/main/java/lsfusion/interop/action/ReportClientAction.java
api/src/main/java/lsfusion/interop/form/print/ReportGenerator.java
api/src/main/java/lsfusion/interop/logics/LogicsSessionObject.java
api/src/main/java/lsfusion/interop/navigator/ClientSettings.java
desktop-client/src/main/java/lsfusion/client/controller/MainController.java
desktop-client/src/main/java/lsfusion/client/controller/dispatch/SwingClientActionDispatcher.java
desktop-client/src/main/java/lsfusion/client/form/controller/ClientFormController.java
server/src/main/java/lsfusion/server/logics/form/open/stat/PrintAction.java
server/src/main/java/lsfusion/server/physics/admin/Settings.java
server/src/main/lsfusion/system/Service.lsf
web-client/src/main/java/lsfusion/gwt/client/controller/remote/action/form/GroupReport.java
web-client/src/main/java/lsfusion/gwt/client/controller/remote/action/navigator/GClientSettings.java
web-client/src/main/java/lsfusion/gwt/client/form/controller/GFormController.java
web-client/src/main/java/lsfusion/gwt/client/view/MainFrame.java
web-client/src/main/java/lsfusion/gwt/server/FileUtils.java
web-client/src/main/java/lsfusion/gwt/server/convert/ClientActionToGwtConverter.java
web-client/src/main/java/lsfusion/gwt/server/form/handlers/GroupReportHandler.java
web-client/src/main/java/lsfusion/gwt/server/navigator/handlers/InitializeNavigatorHandler.java

Settings: jasperReportsIgnorePageMargins to set IGNORE_PAGE_MARGINS option for jasper reports auto export (closes #1215)

Settings: jasperReportsIgnorePageMargins

---

server/src/main/java/lsfusion/server/logics/action/session/DataSession.java
server/src/main/java/lsfusion/server/physics/admin/Settings.java
server/src/main/resources/lsfusion.xml

Added setting to disable creation of Session objects on APPLY

---

server/src/main/java/lsfusion/server/data/expr/where/classes/data/MatchWhere.java
server/src/main/java/lsfusion/server/data/table/IndexOptions.java
server/src/main/java/lsfusion/server/logics/BusinessLogics.java
server/src/main/java/lsfusion/server/logics/classes/data/TSQueryClass.java
server/src/main/java/lsfusion/server/logics/classes/data/TSVectorClass.java
server/src/main/java/lsfusion/server/logics/form/interactive/instance/FormInstance.java
server/src/main/java/lsfusion/server/physics/admin/Settings.java
server/src/main/resources/lsfusion.xml

Replace settings.filterMatchLanguage and settings.tsVectorDictionaryLanguage -> logics.searchLanguage
Add heuristic for searchLanguage and pdfEncoding

Search language
